### ISSUE TITLE
Metrics endpoint

### ISSUE THREAD

**Issue by olimart** [olimart/queenbee-ruby#6]
FYI the gem follows [stripe-ruby gem](https://github.com/stripe/stripe-ruby) logic.

Objective: being able to execute `Queenbee::Metrics.summary(start_date: "2014-07-01", end_date: "2014-07-02")` from the gem.

It should leverage the api_operations `get` which handles all get operations. The idea is to set the url dynamically from the method being called. For example `Queenbee::Metrics.summary` should call `api/metrics/summary` automatically.

Currently, it fails because it seems to execute the request to the endpoint `/orders` instead of `summary`. I could not find why.

See metrics branch.

`metrics_test` (already written) must pass.

**Comment by nazrulcse** [comment]
I have tested Queenbee::Metrics.summary from another dummy app like 
```ruby
class OrdersController < BaseController
   def index 
      Queenbee::Metrics.summary(start_date: "2014-07-01", end_date: "2014-07-02")
   end
end
```
I see it's hit on the summary method of Queenbee::Metrics, I am not sure what actually wrong for you. Could you please explain a bit more, May be I missed the point.

**Comment by olimart** [comment]
you can set up Queenbee app from here https://github.com/olimart/queenbee

When I run the metrics_test I get `NoMethodError: undefined method `code' for nil:NilClass`

**Comment by nazrulcse** [comment]
I got the same error. And i see that the summary method is an empty method. So the response from this method is nil. I think for this reason we got that error. 
Could you please provide me the content of this method or what we expect from this method.

**Comment by olimart** [comment]
if you remove `summary` method then it raises method missing. However, the idea is that `Queenbee::Metrics.summary` should make GET request (see api_operations) to '/api/metrics/summary`

Since I have other methods doing GET call we need a smart way to leverage api_operations/get but still decode the url based on Queenbee::Metrics.summary

**Comment by nazrulcse** [comment]
Hi

I have changed the summary method like this.
```ruby
module Queenbee
  class Metrics < APIResource
    extend Queenbee::APIOperations::Get

    def self.summary(params = {})
      Queenbee::Metrics.get(params,'/metrics/summary')
    end

  end
end
```

Here i hardcode the url because you are using the class as self url and no action name there. If i use self.url then it will return me 
/metricss but we are expecting /metrics/summary.

And Changed your get module like this 

```ruby
module Queenbee
  module APIOperations
    module Get
      #module ClassMethods
        def get(params = {}, token = nil,url)
          response, token = Queenbee.request(:get, url, token, params)
          response
        end
      #end

      # def self.included(base)
      #   base.extend(ClassMethods)
      # end
    end
  end
end

```

Now if i run the test code the the url shows me like this http://localhost:3000/api/metrics/summary. And it return 404 not found. 
Can we please explain me your expection one more time.
